### ISSUE TITLE
LightGraphs reference?

### ISSUE THREAD

**Issue by sbromberger** [abhijithanilkumar/NetworkViz.jl#12]
I can't believe I wasn't aware of this package until today!

@abhijithanilkumar - please take a look at https://github.com/JuliaGraphs/LightGraphs.jl/blob/master/README.md and http://lightgraphsjl.readthedocs.org/en/latest/integration/ - if you'd like to create some PRs to include this package in the "integrations / visualizations" section, I'd be happy to merge them.

**Comment by abhijithanilkumar** [comment]
@sbromberger That'd be nice! I'll make a PR soon.

**Comment by sbromberger** [comment]
Closing since I just merged your PR. Thanks!
