### ISSUE TITLE
Colouring edges and nodes

### ISSUE THREAD

**Issue by abhijithanilkumar** [abhijithanilkumar/NetworkViz.jl#2]
Enable individual colouring of edges and nodes!

**Comment by ranjanan** [comment]
+1

**Comment by abhijithanilkumar** [comment]
@ranjanan I've added coloring support for edges and nodes. Size and shape of nodes can be changed now. Thickness of edges can also be changed!

**Comment by ranjanan** [comment]
Cool, thanks!

On Wed, Apr 6, 2016 at 8:06 PM, Abhijith Anilkumar <notifications@github.com
